#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="${EMBODIED_AGENT_PROJECT_ROOT:-$(cd "${SCRIPT_DIR}/.." && pwd)}"
LEROBOT_ROOT="${EMBODIED_AGENT_LEROBOT_ROOT:-$(cd "${PROJECT_ROOT}/.." && pwd)}"

export EMBODIED_AGENT_PROJECT_ROOT="${PROJECT_ROOT}"
export EMBODIED_AGENT_LEROBOT_ROOT="${LEROBOT_ROOT}"

export EMBODIED_AGENT_LEROBOT_PYTHONPATH="${EMBODIED_AGENT_LEROBOT_PYTHONPATH:-${LEROBOT_ROOT}/src}"
export EMBODIED_AGENT_LEROBOT_CONFIG_PATH="${EMBODIED_AGENT_LEROBOT_CONFIG_PATH:-${PROJECT_ROOT}/lerobot_configs/so101_follower.local.yaml}"
export EMBODIED_AGENT_SMOLVLA_MODEL_PATH="${EMBODIED_AGENT_SMOLVLA_MODEL_PATH:-${PROJECT_ROOT}/outputs/train/hanoi_smolvla_v1_full/checkpoints/010000/pretrained_model}"

export EMBODIED_AGENT_CAMERA_DEVICE_ID="${EMBODIED_AGENT_CAMERA_DEVICE_ID:-/dev/video0}"
export EMBODIED_AGENT_CAMERA_FRAME_ID="${EMBODIED_AGENT_CAMERA_FRAME_ID:-hanoi_overhead_camera}"

export EMBODIED_AGENT_HTTP_HOST="${EMBODIED_AGENT_HTTP_HOST:-127.0.0.1}"
export EMBODIED_AGENT_HTTP_PORT="${EMBODIED_AGENT_HTTP_PORT:-7864}"

# Keep API settings override-friendly. If you already exported them elsewhere,
# sourcing this file will not replace them.
export EMBODIED_AGENT_LLM_FALLBACK_MODEL="${EMBODIED_AGENT_LLM_FALLBACK_MODEL:-gpt-4o-mini}"
export EMBODIED_AGENT_LLM_FALLBACK_API_KEY="${EMBODIED_AGENT_LLM_FALLBACK_API_KEY:-}"
export EMBODIED_AGENT_LLM_FALLBACK_BASE_URL="${EMBODIED_AGENT_LLM_FALLBACK_BASE_URL:-https://api.openai.com/v1}"

export EMBODIED_AGENT_VLM_MODEL="${EMBODIED_AGENT_VLM_MODEL:-gpt-4o}"
export EMBODIED_AGENT_VLM_API_KEY="${EMBODIED_AGENT_VLM_API_KEY:-}"
export EMBODIED_AGENT_VLM_BASE_URL="${EMBODIED_AGENT_VLM_BASE_URL:-https://api.openai.com/v1}"

echo "SmolVLA real-local environment loaded."
echo "  PROJECT_ROOT=${EMBODIED_AGENT_PROJECT_ROOT}"
echo "  EMBODIED_AGENT_LEROBOT_CONFIG_PATH=${EMBODIED_AGENT_LEROBOT_CONFIG_PATH}"
echo "  EMBODIED_AGENT_SMOLVLA_MODEL_PATH=${EMBODIED_AGENT_SMOLVLA_MODEL_PATH}"
echo "  EMBODIED_AGENT_CAMERA_DEVICE_ID=${EMBODIED_AGENT_CAMERA_DEVICE_ID}"
echo "  EMBODIED_AGENT_HTTP_PORT=${EMBODIED_AGENT_HTTP_PORT}"
